; Ibutod

; Kumpigurasyon ng PlatformIO
[platformio]
default_envs = arduino_nano_esp32

; Kumpigurasyon ng Ibinabahaging Kaligiran
[env]
framework = arduino
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra

; Arduino Nano ESP32
; Pangunahing Ineeksperimentong Target
[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
